<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.v5YYcZp' shared service.

return $this->privates['service_locator.v5YYcZp'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array());
