<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJLbvw4H\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJLbvw4H/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJLbvw4H.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerJLbvw4H\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerJLbvw4H\srcProdProjectContainer();
